apiVersion: v1
kind: Service
metadata:
  name: decidim-demo-service
  labels:
    app: decidim-demo
spec:
  type: ClusterIP
  selector:
    app: decidim-demo
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: decidim-demo-deployment
  labels:
    app: decidim-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: decidim-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 34%
      maxUnavailable: 34%
  template:
    metadata:
      name: decidim-demo
      labels:
        app: decidim-demo
    spec:
      containers:
      - name: main
        image: ghcr.io/liquidvotingio/liquid-decidim-demo:latest
        imagePullPolicy: Always
        env:
          - name: APP_HOST
            value: localhost
          - name: DB_HOST
            value: decidim-demo-postgres-svc.default.svc.cluster.local
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: decidim-demo-postgres-config
                key: postgres-dbname
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: decidim-demo-postgres-config
                key: postgres-username
          - name: DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: decidim-demo-postgres-config
                key: postgres-password
          - name: DATABASE_URL
            value: postgres://$(DB_USER):$(DB_PASSWD)@$(DB_HOST):5432/$(DB_NAME)
          - name: REDIS_URL
            value: redis://decidim-demo-redis-svc.default.svc.cluster.local:6379/0
          - name: LINODE_BUCKET_KEY_ID
            valueFrom:
              secretKeyRef:
                name: linode-bucket-config
                key: access-key
          - name: LINODE_BUCKET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: linode-bucket-config
                key: secret-key
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: APP_PORT
            value: "3000"
          - name: SERVICE_NAME
            value: decidim-demo.default.svc.cluster.local
        resources:
          requests:
             cpu: "75m"
        # readinessProbe:
        #   httpGet:
        #     path: /robots.txt
        #     port: 3000
        #     scheme: HTTP
        securityContext:
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      # initContainers:
      # - name: migrations
      #   image: ghcr.io/liquidvotingio/liquid-decidim-demo:latest
      #   command:
      #   - rake
      #   - db:abort_if_pending_migrations
      imagePullSecrets:
      - name: registry-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
